version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - '1234:1234'
  postgresql:
    build:
      context: .
      dockerfile: postgresql.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexplore_test
  web:
    build:
      context: .
      dockerfile: duty-list.Dockerfile
    ports:
      - '8080:80'
